### ISSUE TITLE
Adding the username and password to the transmission

### ISSUE THREAD

**Issue by Hydrahail-Johnson** [wiserain/docker-transmission#1]
I use the transmission with flexget in the dockerhub of this link.
"https://registry.hub.docker.com/r/wiserain/transmission"
But, I can not add the username and password for the transmission. It won't be worked either by editing the "setting.json" or editing the environment of the container of the transmission.

What should I do?

**Comment by wiserain** [comment]
If you tried it by editing "settings.json", you should stop transmission daemon and then start after finished editing. 

As you can see here in https://github.com/wiserain/docker-transmission/blob/00bcfc19f099703fc1b58ec85bcfc013740d3a77/Dockerfile#L5, flexget is added upon linuxserver/transmission without modifying any of it. Therefore, I have no idea what's the problem. The method using environment variables ```USER``` and ```PASS``` works well in my case.
